
signature_rules = [
    {"pattern": b"/etc/passwd", "msg": "Potential Directory Traversal Attack: Attempt to access system password file."},
    {"pattern": b"SELECT * FROM users", "msg": "Potential SQL Injection Attack: Attempt to retrieve all records from the 'users' table."},
    {"pattern": b"DROP TABLE", "msg": "Potential SQL Injection Attack: Attempt to drop a database table."},
    {"pattern": b"cmd.exe", "msg": "Potential Command Injection Attack: Attempt to execute a system command on Windows."},
    {"pattern": b"; exec(", "msg": "Potential Command Injection Attack: Attempt to execute a system command on Unix."},
    {"pattern": b"passwd:", "msg": "Potential Password Leak: Identification of 'passwd:' keyword in the payload."},
    {"pattern": b"ssh-rsa", "msg": "Potential SSH Key Exchange: Identification of SSH RSA key exchange."},
    {"pattern": b"SELECT * FROM passwords", "msg": "Potential SQL Injection Attack: Attempt to retrieve all records from the 'passwords' table."},
    {"pattern": b"/bin/sh", "msg": "Potential Command Injection Attack: Attempt to execute a shell command."},
    {"pattern": b"/etc/shadow", "msg": "Potential Directory Traversal Attack: Attempt to access system password hash file."},
    {"pattern": b"UNION ALL SELECT", "msg": "Potential SQL Injection Attack: Attempt to perform a UNION-based SQL injection."},
    {"pattern": b"<script>alert(", "msg": "Potential Cross-Site Scripting (XSS) Attack: Attempt to execute a JavaScript alert."},
    {"pattern": b"DELETE FROM", "msg": "Potential SQL Injection Attack: Attempt to delete records from a database table."},
    {"pattern": b"exec sp_", "msg": "Potential SQL Injection Attack: Attempt to execute a stored procedure in SQL Server."},
    {"pattern": b"/bin/bash", "msg": "Potential Command Injection Attack: Attempt to execute a bash command."},
    {"pattern": b"ORA-", "msg": "Potential Oracle Database Error: Identification of 'ORA-' error message."},
    {"pattern": b"ALTER TABLE", "msg": "Potential SQL Injection Attack: Attempt to alter database table structure."},
    {"pattern": b"<script>window.location", "msg": "Potential Redirection Attack: Attempt to redirect the user to another page."},
    {"pattern": b"admin' OR '1'='1", "msg": "Potential SQL Injection Attack: Attempt to bypass authentication."},
    {"pattern": b"root:", "msg": "Potential Privilege Escalation: Identification of 'root:' keyword in the payload."},
    {"pattern": b"GET /etc/passwd", "msg": "Potential Directory Traversal Attack: Attempt to retrieve system password file via HTTP GET request."},
    {"pattern": b"127.0.0.1", "msg": "Potential Localhost Access: Identification of '127.0.0.1' IP address in the payload."},
    {"pattern": b"SELECT * FROM information_schema", "msg": "Potential SQL Injection Attack: Attempt to retrieve database schema information."},
    {"pattern": b"<script>document.cookie", "msg": "Potential Cross-Site Scripting (XSS) Attack: Attempt to access user cookies."},
    {"pattern": b"UPDATE users SET password", "msg": "Potential SQL Injection Attack: Attempt to update user passwords."},
    {"pattern": b"DROP DATABASE", "msg": "Potential SQL Injection Attack: Attempt to drop the entire database."},
    {"pattern": b"<script>window.open(", "msg": "Potential Pop-up Window Attack: Attempt to open a new browser window."},
    {"pattern": b"DELETE FROM users", "msg": "Potential SQL Injection Attack: Attempt to delete all records from the 'users' table."},
    {"pattern": b"xp_cmdshell", "msg": "Potential Command Injection Attack: Attempt to execute a system command using xp_cmdshell in SQL Server."},
    {"pattern": b"INSERT INTO", "msg": "Potential SQL Injection Attack: Attempt to insert records into a database table."},
    {"pattern": b"SELECT @@version", "msg": "Potential SQL Injection Attack: Attempt to retrieve the database version."},
    {"pattern": b"<script>document.write(", "msg": "Potential Cross-Site Scripting (XSS) Attack: Attempt to dynamically write content to the webpage."},
    {"pattern": b"ALTER DATABASE", "msg": "Potential SQL Injection Attack: Attempt to alter the database."},
    {"pattern": b"eval(", "msg": "Potential Code Injection Attack: Attempt to execute dynamically generated code."},
    {"pattern": b"window.location.href=", "msg": "Potential Redirection Attack: Attempt to change the browser's location."},
    {"pattern": b"UNION SELECT", "msg": "Potential SQL Injection Attack: Attempt to perform a UNION-based SQL injection."},
    {"pattern": b"sudo", "msg": "Potential Privilege Escalation: Identification of 'sudo' command usage."},
    {"pattern": b"CREATE TABLE", "msg": "Potential SQL Injection Attack: Attempt to create a new database table."},
    {"pattern": b"document.write(", "msg": "Potential Cross-Site Scripting (XSS) Attack: Attempt to write content to the webpage."},
    {"pattern": b"EXECUTE AS", "msg": "Potential SQL Injection Attack: Attempt to execute as a different user in SQL Server."},
    {"pattern": b"mongodb://", "msg": "Potential MongoDB Connection String: Identification of MongoDB connection string."},
    {"pattern": b"chmod", "msg": "Potential File Permission Modification: Identification of 'chmod' command usage."},
    {"pattern": b"GET /etc/shadow", "msg": "Potential Directory Traversal Attack: Attempt to retrieve system password hash file via HTTP GET request."},
    {"pattern": b"xp_regread", "msg": "Potential Registry Access: Attempt to read from the Windows registry."},
    {"pattern": b"db.collection('users').find(", "msg": "Potential MongoDB Query: Attempt to retrieve data from a MongoDB collection."},
    {"pattern": b"rm -rf", "msg": "Potential File Deletion: Identification of 'rm -rf' command usage."},
    {"pattern": b"<iframe src=", "msg": "Potential Clickjacking Attack: Attempt to load content in an invisible iframe."},
    {"pattern": b"ALTER INDEX", "msg": "Potential SQL Injection Attack: Attempt to alter database index."},
    {"pattern": b"sudo su -", "msg": "Potential Privilege Escalation: Identification of 'sudo su -' command usage."},
    {"pattern": b"DELETE * FROM", "msg": "Potential SQL Injection Attack: Attempt to delete all records from a database table."},
    {"pattern": b"mongo --version", "msg": "Potential MongoDB Version Check: Identification of MongoDB version check command."},
    {"pattern": b"ALTER LOGIN", "msg": "Potential SQL Injection Attack: Attempt to alter login credentials in SQL Server."},
    {"pattern": b"cat /etc/passwd", "msg": "Potential Directory Traversal Attack: Attempt to read system password file."},
    {"pattern": b"document.location.href=", "msg": "Potential Redirection Attack: Attempt to change the browser's location."},
    {"pattern": b"mysql -u", "msg": "Potential MySQL Connection: Identification of MySQL connection attempt."},
    {"pattern": b"GRANT ALL PRIVILEGES", "msg": "Potential SQL Injection Attack: Attempt to grant all privileges in SQL."},
    {"pattern": b"mongodump", "msg": "Potential MongoDB Backup: Identification of MongoDB backup command."},
    {"pattern": b"wget http://", "msg": "Potential Malicious File Download: Attempt to download file from HTTP."},
    {"pattern": b"CREATE INDEX", "msg": "Potential SQL Injection Attack: Attempt to create a new database index."},
    {"pattern": b"system(", "msg": "Potential Command Injection Attack: Attempt to execute a system command."},
    {"pattern": b"echo root:", "msg": "Potential Privilege Escalation: Identification of 'echo root:' command usage."},
    {"pattern": b"INSERT INTO users VALUES", "msg": "Potential SQL Injection Attack: Attempt to insert values into the 'users' table."},
    {"pattern": b"telnet ", "msg": "Potential Telnet Connection: Identification of telnet connection attempt."},
    {"pattern": b"db.createUser(", "msg": "Potential MongoDB User Creation: Attempt to create a new user in MongoDB."},
    {"pattern": b"arp -a", "msg": "Potential ARP Spoofing: Identification of ARP cache inspection command."},
    {"pattern": b"ftp ", "msg": "Potential FTP Connection: Identification of FTP connection attempt."},
    {"pattern": b"SELECT @@global.", "msg": "Potential SQL Injection Attack: Attempt to retrieve global variable in SQL."},
    {"pattern": b"INSERT INTO users", "msg": "Potential SQL Injection Attack: Attempt to insert records into the 'users' table."},
    {"pattern": b"rm -rf /", "msg": "Potential File Deletion: Identification of attempt to delete all files in the system."},
    {"pattern": b"curl -O", "msg": "Potential File Download: Identification of file download using cURL."},
    {"pattern": b"systeminfo", "msg": "Potential System Information Retrieval: Identification of systeminfo command usage."},
    {"pattern": b"db.users.insert(", "msg": "Potential MongoDB User Insertion: Attempt to insert data into the 'users' collection in MongoDB."},
{"pattern": b"SELECT @@local.", "msg": "Potential SQL Injection Attack: Attempt to retrieve local variable in SQL."},
    {"pattern": b"mysql -h", "msg": "Potential MySQL Connection: Identification of MySQL connection to a specific host."},
    {"pattern": b"exec(", "msg": "Potential Command Injection Attack: Attempt to execute a system command."},
    {"pattern": b"systeminfo | findstr", "msg": "Potential System Information Retrieval: Identification of systeminfo command usage with filter."},
    {"pattern": b"db.runCommand(", "msg": "Potential MongoDB Command Execution: Attempt to execute a MongoDB command."},
    {"pattern": b"scp ", "msg": "Potential SCP File Transfer: Identification of SCP file transfer command."},
    {"pattern": b"phpinfo()", "msg": "Potential PHP Information Leakage: Identification of phpinfo() function usage."},
    {"pattern": b"java -jar", "msg": "Potential Java Jar Execution: Identification of Java JAR file execution."},
    {"pattern": b"INSERT INTO users (username", "msg": "Potential SQL Injection Attack: Attempt to insert records into the 'users' table with specific columns."},
    {"pattern": b"SELECT column_name FROM information_schema.columns", "msg": "Potential SQL Injection Attack: Attempt to retrieve column names from information_schema.columns."},
    {"pattern": b"db.dropDatabase(", "msg": "Potential MongoDB Database Deletion: Attempt to drop a MongoDB database."},
    {"pattern": b"ftp://", "msg": "Potential FTP Connection: Identification of FTP connection attempt with protocol."},
    {"pattern": b"CREATE USER", "msg": "Potential SQL Injection Attack: Attempt to create a new user in SQL."},
    {"pattern": b"chmod 777", "msg": "Potential File Permission Modification: Identification of 'chmod' command with full access."},
    {"pattern": b"SELECT * FROM sys.databases", "msg": "Potential SQL Injection Attack: Attempt to retrieve all databases in SQL Server."},
    {"pattern": b"db.createCollection(", "msg": "Potential MongoDB Collection Creation: Attempt to create a new collection in MongoDB."},
    {"pattern": b"ps -ef", "msg": "Potential Process Listing: Identification of process listing command."},
    {"pattern": b"php -r", "msg": "Potential PHP Command Execution: Identification of PHP command execution."},
    {"pattern": b"GRANT ALL ON", "msg": "Potential SQL Injection Attack: Attempt to grant all privileges on a database object."},
    {"pattern": b"ldap://", "msg": "Potential LDAP Connection: Identification of LDAP connection attempt."},
    {"pattern": b"mongo -u", "msg": "Potential MongoDB Connection: Identification of MongoDB connection attempt with authentication."},
    {"pattern": b"GRANT EXECUTE ON", "msg": "Potential SQL Injection Attack: Attempt to grant execute privilege on a database object."},
    {"pattern": b"ssh ", "msg": "Potential SSH Connection: Identification of SSH connection attempt."},
    {"pattern": b"\\$GLOBALS", "msg": "Potential PHP Global Variable Usage: Identification of global variable usage in PHP."},
    {"pattern": b"db.collection.drop(", "msg": "Potential MongoDB Collection Deletion: Attempt to drop a MongoDB collection."},
    {"pattern": b"cat /etc/shadow", "msg": "Potential File Access: Identification of attempt to read system shadow file."},
    {"pattern": b"ALTER USER", "msg": "Potential SQL Injection Attack: Attempt to alter user in SQL."},
    {"pattern": b"git clone", "msg": "Potential Git Repository Cloning: Identification of Git repository cloning command."},
    {"pattern": b"system('id')", "msg": "Potential Command Execution: Identification of system() command execution with 'id'."},
    {"pattern": b"SELECT @@hostname", "msg": "Potential SQL Injection Attack: Attempt to retrieve the database hostname."},
    {"pattern": b"nc -lvp", "msg": "Potential Netcat Listener: Identification of Netcat listener command."},
    {"pattern": b"java.lang.Runtime.getRuntime().exec(", "msg": "Potential Java Command Execution: Identification of Java Runtime command execution."},
    {"pattern": b"invoke-expression", "msg": "Potential PowerShell Command Execution: Identification of Invoke-Expression command in PowerShell."},
    {"pattern": b"db.dropUser(", "msg": "Potential MongoDB User Deletion: Attempt to drop a user in MongoDB."},
    {"pattern": b"GET /etc/shadow", "msg": "Potential File Access: Identification of HTTP GET request for system shadow file."},
    {"pattern": b"SELECT @@version_comment", "msg": "Potential SQL Injection Attack: Attempt to retrieve the database version comment."},
    {"pattern": b"INSERT INTO user", "msg": "Potential SQL Injection Attack: Attempt to insert records into the 'user' table."},
    {"pattern": b"awk '{print $1}'", "msg": "Potential Command Execution: Identification of AWK command execution."},
    {"pattern": b"exec sp_", "msg": "Potential SQL Injection Attack: Attempt to execute a stored procedure in SQL Server."},
    {"pattern": b"mongo --port", "msg": "Potential MongoDB Connection: Identification of MongoDB connection attempt with specific port."},
    {"pattern": b"GET /etc/passwd", "msg": "Potential File Access: Identification of HTTP GET request for system password file."},
    {"pattern": b"SELECT host_name FROM information_schema", "msg": "Potential SQL Injection Attack: Attempt to retrieve host name from information_schema."},
    {"pattern": b"\\$_POST", "msg": "Potential PHP Global Variable Usage: Identification of POST global variable usage in PHP."},
    {"pattern": b"USE master", "msg": "Potential SQL Injection Attack: Attempt to use the 'master' database in SQL Server."},
    {"pattern": b"ncat -lvp", "msg": "Potential Netcat Listener: Identification of Ncat listener command."},
    {"pattern": b"db.auth(", "msg": "Potential MongoDB Authentication: Attempt to authenticate in MongoDB."},
    {"pattern": b"SELECT @@max_connections", "msg": "Potential SQL Injection Attack: Attempt to retrieve the maximum connections allowed."},
    {"pattern": b"scp -r", "msg": "Potential SCP Recursive File Transfer: Identification of SCP file transfer command with recursion."},
    {"pattern": b"system('whoami')", "msg": "Potential Command Execution: Identification of system() command execution with 'whoami'."},
    {"pattern": b"java.io.File", "msg": "Potential File Handling: Identification of Java file manipulation code."},
    {"pattern": b"\"; net user", "msg": "Potential Command Injection: Identification of command injection attempt with 'net user'."},
    {"pattern": b"SELECT @@datadir", "msg": "Potential SQL Injection Attack: Attempt to retrieve the database data directory."},
    {"pattern": b"\\$GET", "msg": "Potential PHP Global Variable Usage: Identification of GET global variable usage in PHP."},
    {"pattern": b"GRANT ALL ON *", "msg": "Potential SQL Injection Attack: Attempt to grant all privileges on all database objects."},
        {"pattern": b"ssh-keygen", "msg": "Potential SSH Key Generation: Identification of SSH key generation command."},
    {"pattern": b"exec('id')", "msg": "Potential Command Execution: Identification of exec() command execution with 'id'."},
    {"pattern": b"UPDATE ", "msg": "Potential SQL Injection Attack: Attempt to update records in a database table."},
    {"pattern": b"\\$_REQUEST", "msg": "Potential PHP Global Variable Usage: Identification of REQUEST global variable usage in PHP."},
    {"pattern": b"CREATE DATABASE", "msg": "Potential SQL Injection Attack: Attempt to create a new database."},
    {"pattern": b"sudo su", "msg": "Potential Privilege Escalation: Identification of 'sudo su' command usage."},
    {"pattern": b"psql -h", "msg": "Potential PostgreSQL Connection: Identification of PostgreSQL connection attempt to a specific host."},
    {"pattern": b"system('ls')", "msg": "Potential Command Execution: Identification of system() command execution with 'ls'."},
    {"pattern": b"\\$POST", "msg": "Potential PHP Global Variable Usage: Identification of POST global variable usage in PHP."},
    {"pattern": b"ssh -l", "msg": "Potential SSH Connection: Identification of SSH connection attempt with specific username."},
    {"pattern": b"scp -t", "msg": "Potential SCP File Transfer: Identification of SCP file transfer command with target."},
    {"pattern": b"\\$\\$_GET", "msg": "Potential PHP Global Variable Usage: Identification of GET global variable usage in PHP."},
    {"pattern": b"db.getSiblingDB(", "msg": "Potential MongoDB Database Access: Attempt to access a sibling database in MongoDB."},
    {"pattern": b"db.eval(", "msg": "Potential MongoDB Code Execution: Attempt to execute code in MongoDB using eval."},
    {"pattern": b"\\$\\$_POST", "msg": "Potential PHP Global Variable Usage: Identification of POST global variable usage in PHP."},
    {"pattern": b"curl -d", "msg": "Potential HTTP POST Request: Identification of cURL POST request."},
    {"pattern": b"tftp ", "msg": "Potential TFTP Connection: Identification of TFTP connection attempt."},
    {"pattern": b"sudo -u", "msg": "Potential Privilege Escalation: Identification of 'sudo -u' command usage."},
    {"pattern": b"CREATE INDEX ", "msg": "Potential SQL Injection Attack: Attempt to create an index in a database table."},
    {"pattern": b"system('cat /etc/passwd')", "msg": "Potential Command Execution: Identification of system() command execution with 'cat /etc/passwd'."},
    {"pattern": b"pg_dump -h", "msg": "Potential PostgreSQL Dump: Identification of PostgreSQL database dump command with specific host."},
    {"pattern": b"\\$_GET", "msg": "Potential PHP Global Variable Usage: Identification of GET global variable usage in PHP."},
    {"pattern": b"\\$_COOKIE", "msg": "Potential PHP Global Variable Usage: Identification of COOKIE global variable usage in PHP."},
    {"pattern": b"sqlmap ", "msg": "Potential SQL Injection Tool: Identification of SQL injection testing tool usage."},
    {"pattern": b"db.collection.remove(", "msg": "Potential MongoDB Data Deletion: Attempt to remove data from a MongoDB collection."},
    {"pattern": b"SELECT * FROM mysql.user", "msg": "Potential SQL Injection Attack: Attempt to retrieve user information from MySQL."},
    {"pattern": b"db.system.js.save(", "msg": "Potential MongoDB JavaScript Injection: Attempt to save a JavaScript function in MongoDB."},
    {"pattern": b"CREATE USER ", "msg": "Potential SQL Injection Attack: Attempt to create a new user in SQL."},
    {"pattern": b"system('whoami')", "msg": "Potential Command Execution: Identification of system() command execution with 'whoami'."},
    {"pattern": b"SELECT @@hostname", "msg": "Potential SQL Injection Attack: Attempt to retrieve the database hostname."},
    {"pattern": b"\\$\\$_COOKIE", "msg": "Potential PHP Global Variable Usage: Identification of COOKIE global variable usage in PHP."},
    {"pattern": b"mysql -D", "msg": "Potential MySQL Connection: Identification of MySQL connection to a specific database."},
    {"pattern": b"ssh -i", "msg": "Potential SSH Connection: Identification of SSH connection attempt with identity file."},
    {"pattern": b"scp -S", "msg": "Potential SCP File Transfer: Identification of SCP file transfer command with specific shell."},
    {"pattern": b"php -a", "msg": "Potential PHP Interactive Shell: Identification of PHP interactive shell usage."},
    {"pattern": b"SELECT * FROM mysql.db", "msg": "Potential SQL Injection Attack: Attempt to retrieve database information from MySQL."},
    {"pattern": b"sqlmap.py ", "msg": "Potential SQL Injection Tool: Identification of SQL injection testing tool usage (Python version)."},
    {"pattern": b"db.collection.insertOne(", "msg": "Potential MongoDB Data Insertion: Attempt to insert data into a MongoDB collection."},
    {"pattern": b"CREATE VIEW ", "msg": "Potential SQL Injection Attack: Attempt to create a new view in SQL."},
    {"pattern": b"system('net user')", "msg": "Potential Command Execution: Identification of system() command execution with 'net user'."},
    {"pattern": b"SELECT * FROM mysql.tables_priv", "msg": "Potential SQL Injection Attack: Attempt to retrieve table privilege information from MySQL."},
    {"pattern": b"db.system.js.remove(", "msg": "Potential MongoDB JavaScript Injection: Attempt to remove a JavaScript function from MongoDB."},
    {"pattern": b"system('pwd')", "msg": "Potential Command Execution: Identification of system() command execution with 'pwd'."},
    {"pattern": b"\\$\\$_REQUEST", "msg": "Potential PHP Global Variable Usage: Identification of REQUEST global variable usage in PHP."},
    {"pattern": b"mysql --host", "msg": "Potential MySQL Connection: Identification of MySQL connection attempt with specific host."},
    {"pattern": b"ssh -F", "msg": "Potential SSH Connection: Identification of SSH connection attempt with specific configuration file."},
    {"pattern": b"scp -P", "msg": "Potential SCP File Transfer: Identification of SCP file transfer command with specific port."},
    {"pattern": b"\\$\\$_SESSION", "msg": "Potential PHP Global Variable Usage: Identification of SESSION global variable usage in PHP."},
    {"pattern": b"system('who')", "msg": "Potential Command Execution: Identification of system() command execution with 'who'."},
    {"pattern": b"mysql -p", "msg": "Potential MySQL Connection: Identification of MySQL connection attempt with password prompt."},
    {"pattern": b"ssh -o", "msg": "Potential SSH Connection: Identification of SSH connection attempt with specific options."},
    {"pattern": b"scp -q", "msg": "Potential SCP File Transfer: Identification of SCP file transfer command with quiet mode."},
]
